#!/usr/bin/env python3
"""
render.py · 从唯一真源生成派生视图（只读真源，可重复运行）

registry.yaml 是唯一真源。本脚本把它展开成人读的文件，并且：

  --check   重新生成并与磁盘上现有内容逐字比较，不一致就非零退出

生成原则：**生成区不得手工编辑。** 手改会在下一次 --check 时被报出来，
所以不存在「生成区和真源对不上」这种需要人去核对的状态。

用法:
  python3 scripts/render.py            # 生成
  python3 scripts/render.py --check    # 核对，不写盘
"""

import sys, argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("需要 pyyaml：python3 -m pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent


def read(p):
    return p.read_text(encoding="utf-8")
REGISTRY = ROOT / "workflow" / "registry.yaml"

BEGIN = "<!-- BEGIN:generated by scripts/render.py · 请勿手工编辑 -->"
END = "<!-- END:generated -->"


def phase_doc(ph, reg):
    a_by_id = {a["id"]: a for a in reg["artifacts"]}
    r_by_id = {r["id"]: r for r in reg["roles"]}
    s_by_id = {s["id"]: s for s in reg["skills"]}
    pr_by_id = {p["id"]: p for p in reg["principles"]}

    L = [f"# {ph['id']} · {ph['name']}（{ph['zh']}）", ""]
    L.append(f"> {ph['purpose']}")
    L.append("")

    L.append("## 开工前必须已在手")
    if ph.get("required_inputs"):
        for aid in ph["required_inputs"]:
            a = a_by_id[aid]
            L.append(f"- **{aid} {a['zh']}** —— 产出方 `{a['producer']}`。"
                     f"拿不到就退回，不要靠猜补齐。")
    else:
        L.append("- 无。这是入口阶段。")
    L.append("")

    L.append("## 默认装配")
    L.append("")
    L.append("| 角色 | 心智模型 | 可用技能 |")
    L.append("|---|---|---|")
    for rid in ph.get("default_roles", []):
        r = r_by_id[rid]
        sk = "、".join(f"`{x}`" for x in r.get("skills", [])) or "—"
        L.append(f"| `{rid}` {r['zh']} | "
                 f"{len(r.get('principles', []))} 条 | {sk} |")
    L.append("")
    L.append("阶段只规定判据，不绑定角色。换人换会话，判据不变。")
    L.append("")

    L.append("## 退出判据")
    L.append("")
    for c in ph.get("exit_criteria", []):
        L.append(f"- {c}")
    L.append("")
    if ph.get("hard_rules"):
        L.append("## 硬规则")
        L.append("")
        for h in ph["hard_rules"]:
            L.append(f"- {h}")
        L.append("")

    L.append("## 产出")
    L.append("")
    for aid in ph.get("produces", []):
        a = a_by_id[aid]
        L.append(f"### {aid} · {a['zh']}（`{a['key']}`）")
        L.append("")
        L.append(f"产出方：`{a['producer']}`　持久性：`{a['persistence']}`"
                 f"{'（append-only）' if a.get('append_only') else ''}")
        L.append("")
        L.append("| 字段 | 含义 |")
        L.append("|---|---|")
        for f in a["fields"]:
            L.append(f"| `{f}` | {a.get('notes', {}).get(f, '')} |")
        L.append("")
    if not ph.get("produces"):
        L.append("- 无。本阶段不新增产物，它消费上游已经冻结的东西。")
        L.append("")

    L.append("---")
    L.append(BEGIN)
    L.append(f"<!-- 阶段 {ph['id']} 的结构由 workflow/registry.yaml 派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def ribbon_doc(rb, reg):
    s_by_id = {s["id"]: s for s in reg["skills"]}
    L = [f"# 横切带 · {rb['zh']}（`{rb['id']}`）", ""]
    L.append(f"> {rb['why']}")
    L.append("")
    L.append(f"常驻：`{'是' if rb.get('always') else '否'}`")
    if not rb.get("always"):
        L.append(f"适用范围：{', '.join(rb.get('applies_to', []))}")
    L.append("")
    L.append("## 携带的技能")
    L.append("")
    for sid in rb.get("skills", []):
        s = s_by_id[sid]
        L.append(f"- `{sid}` **{s['zh']}** —— {s['summary']}")
    L.append("")
    L.append("横切带不属于任何阶段：它随装配进入，会话结束后不留下需要「完成」的东西。")
    L.append("")
    L.append("---")
    L.append(BEGIN)
    L.append(f"<!-- 横切带 {rb['id']} 的结构由 workflow/registry.yaml 派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def artifacts_doc(reg):
    a_by_id = {a["id"]: a for a in reg["artifacts"]}
    L = ["# 集合 A · 工作流的全部产物", "",
         "一个**产物**不是一份文件，是「一组字段 + 谁产出 + 谁消费 + 活多久」。",
         "它落在下游仓库的哪个路径，由 `driver` 按集合 B 裁定——",
         "纪律是本库的，位置是下游的。见 [下游映射](downstream-mapping.md)。", ""]
    L.append("## 总表")
    L.append("")
    L.append("| id | 产物 | 产出方 | 消费者 | 持久性 | 为什么需要它 |")
    L.append("|---|---|---|---|---|---|")
    for a in reg["artifacts"]:
        L.append(f"| {a['id']} | **{a['zh']}** `{a['key']}` | `{a['producer']}` | "
                 f"{'、'.join(a['consumers'])} | `{a['persistence']}`"
                 f"{' append-only' if a.get('append_only') else ''} | {a['rationale']} |")
    L.append("")
    L.append("## 字段")
    L.append("")
    for a in reg["artifacts"]:
        L.append(f"### {a['id']} · {a['zh']}")
        L.append("")
        for f in a["fields"]:
            L.append(f"- `{f}` — {a.get('notes', {}).get(f, '')}")
        L.append("")
    L.append("## 落盘形状：每类产物该是文件还是目录")
    L.append("")
    L.append("产物不是文件也不是目录——它是「字段 + 产出方 + 消费者 + 存活期」。"
             "但它最终要落在磁盘上，形状必须定死，否则装配者各自发明，"
             "一个小任务就能建出八九个文件。")
    L.append("")
    L.append("| 形状 | 产物 | 为什么 |")
    L.append("|---|---|---|")
    for shape, ids, why in [
        ("单文件", ["A9"], "append-only。拆成每任务一个就断了「全程记录不丢」，"
                            "也没法跨任务重建判断依据。"),
        ("目录", ["A3"], "项目级、跨任务复用、持续增量。合成单文件就成了没人更新的巨型文档。"),
        ("目录", ["A6", "A7", "A8"], "不同片、不同轮会持续产出候选与裁决。"
                                     "而且三者必须物理隔离——实现者不能在自己的文件里写裁决。"),
        ("可合并的包", ["A1", "A2", "A4", "A5"],
         "同一次任务、同一批读者，没有隔离理由。可合成一个 task packet。"),
    ]:
        names = "、".join(f"{i} {a_by_id[i]['zh']}" for i in ids if i in a_by_id)
        L.append(f"| **{shape}** | {names} | {why} |")
    L.append("")
    L.append("**硬约束只有三条**：`A6`/`A7`/`A8` 互不同文件；`A9` 谁都不能合并；其余可随意合并。")
    L.append("")
    L.append("其余产物类别的形状由 `driver` 按下游文档体系裁定——本库不定下游的目录结构。")
    L.append("")
    L.append("### 每类产物的落盘形态")
    L.append("")
    L.append("同一个产物可以有几种落盘形态。**形态不是新产物**——它们回答的是「同样这几栏，")
    L.append("换个落法」，不是「另一个东西」。把它们算成新产物，产物数就会从 9 涨到 20 出头，")
    L.append("而且每一份都会和它的本体各自漂移。")
    L.append("")
    for a in reg["artifacts"]:
        if a.get("embodiment"):
            L.append(f"**{a['id']} {a['zh']}**　—　{a['embodiment']}")
            L.append("")
    L.append("")
    L.append("## 三条不可协商的落盘纪律")
    L.append("")
    L.append("1. **`durable` 的产物必须有可追溯的落点，并进版本库。** 找不到位置就问 Owner，"
             "不要塞进临时目录——丢掉的记录等于没做过。")
    L.append("2. **不许出现「活不过跨会话的产物」。** 本库每一类产物都会被下一个会话读："
             "`P4` 要审 `A6`、`P5` 要验它、`P6` 要发它。把判断输入留在会话里，"
             "等于让下一次接手的人从零重建。")
    L.append("3. **台账只追加。** 不修改、不删除既有行。写错了就再写一行说明为什么错。")
    L.append("")
    L.append("---")
    L.append(BEGIN)
    L.append("<!-- 本文件由 workflow/registry.yaml 的 artifacts 段派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def closure_doc(reg):
    """闭包报告。每一列都要如实对���口径——上一版把「产出阶段」填进
    「在哪一步被校验」那一列，列名与值不符，比没有这一列更坏。"""
    a_by_id = {a["id"]: a for a in reg["artifacts"]}
    rb_produced = {a for rb in reg["ribbons"] if rb.get("always") for a in rb.get("produces", [])}
    producer_phase = {}
    for ph in reg["phases"]:
        for aid in ph.get("produces", []):
            producer_phase.setdefault(aid, ph["id"])
    validated_at = {}
    for ph in reg["phases"]:
        for crit in ph.get("exit_criteria", []):
            for tok in crit.split():
                if len(tok) > 2 and tok[:2] in ("A1","A2","A3","A4","A5","A6","A7","A8","A9") and "." in tok:
                    aid = tok.split(".")[0]
                    if ph["id"] not in validated_at.setdefault(aid, []):
                        validated_at[aid].append(ph["id"])

    L = ["# 闭包报告", "",
         "这份报告回答一个问题：**这套工作流通不通？**",
         "由 `workflow/registry.yaml` 派生，被 `check-closure.py` 的 C2/C3/C4 核对。", "",
         "## 产物链", "",
         "| 产物 | 落盘形状 | 谁产出 | 谁消费 | 在哪一步被校验 |", "|---|---|---|---|---|"]
    for a in reg["artifacts"]:
        aid = a["id"]
        made = "常驻横切带" if aid in rb_produced else producer_phase.get(aid, "**没有任何阶段产出它**")
        checks = "、".join(validated_at.get(aid, [])) or "**无任何阶段校验它**"
        L.append(f"| **{aid} {a['zh']}** | {a.get('shape','未声明')} | `{a['producer']}` | "
                 f"{'、'.join(a['consumers'])} | {checks} |")
    L += ["", "三条读法：", "",
          "- **「谁产出」是唯一性断言**：每个产物只有一个主产出角色（C2/C5 核对）。",
          "- **「在哪一步被校验」是闭合性断言**：产出它的阶段必须在自己的退出判据里校验它，"
          "否则下游拿到的是一份没人验证过的东西（C4 核对）。",
          "- 写成**粗体**的空值不是排版问题：表示有断言未成立，检查器会红。", "",
          "## 阶段链", "",
          "| 阶段 | 开工需要 | 产出 | 默认装配 | 硬规则 |", "|---|---|---|---|---|"]
    for ph in reg["phases"]:
        L.append(f"| **{ph['id']} {ph['name']}** | {'、'.join(ph.get('required_inputs', [])) or '—'} | "
                 f"{'、'.join(ph.get('produces', [])) or '—'} | {'、'.join(ph.get('default_roles', []))} | "
                 f"{'；'.join(ph.get('hard_rules', [])) or '—'} |")
    L += ["", "## 返工回边", "",
          "`A7` 附条件通过时回到 `P3` 重做，走新一轮 P3→P4。",
          "这条边**刻意不建成消费关系**——它是阶段图上的回边，"
          "建进 `consumers` 会让线性可达性检查失效。", "",
          "---", "", BEGIN, "<!-- 本文件由 workflow/registry.yaml 派生 -->", END, ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    reg = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))

    targets = {}
    for ph in reg["phases"]:
        targets[ROOT / "workflow" / "phases" / f"{ph['id']}.md"] = phase_doc(ph, reg)
    for rb in reg["ribbons"]:
        targets[ROOT / "workflow" / "ribbons" / f"{rb['id']}.md"] = ribbon_doc(rb, reg)
    targets[ROOT / "docs" / "artifacts.md"] = artifacts_doc(reg)
    targets[ROOT / "docs" / "closure-report.md"] = closure_doc(reg)

    problems = []
    for path, content in sorted(targets.items()):
        if args.check:
            if not path.is_file():
                problems.append(f"{path.relative_to(ROOT)} 不存在")
            elif read(path) != content:
                problems.append(f"{path.relative_to(ROOT)} 与真源不一致")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.is_file() and read(path) == content:
                continue
            path.write_text(content, encoding="utf-8")
            print(f"生成 {path.relative_to(ROOT)}")

    if args.check:
        if problems:
            print("render --check: FAIL")
            for p in problems:
                print(f"  ↳ {p}")
            return 1
        print(f"render --check: OK（{len(targets)} 个派生文件逐字一致）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
