#!/usr/bin/env python3
"""
render.py · 从唯一真源生成派生视图（只读真源，可重复运行）

registry.yaml 是唯一真源。本脚本把它展开成人读的文件，并且：

  --check   重新生成并与磁盘上现有内容逐字比较，不一致就非零退出

生成原则：**生成区不得手工编辑。** 手改会在下一次 --check 时被报出来，
所以不存在「生成区和真源对不上」这种需要人去核对的状态。

用法:
  python3 scripts/render.py            # 生成
  python3 scripts/render.py --check    # 核对，不写盘
"""

import sys, argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("需要 pyyaml：python3 -m pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent


def read(p):
    return p.read_text(encoding="utf-8")
REGISTRY = ROOT / "workflow" / "registry.yaml"

BEGIN = "<!-- BEGIN:generated by scripts/render.py · 请勿手工编辑 -->"
END = "<!-- END:generated -->"


def phase_doc(ph, reg):
    a_by_id = {a["id"]: a for a in reg["artifacts"]}
    r_by_id = {r["id"]: r for r in reg["roles"]}
    s_by_id = {s["id"]: s for s in reg["skills"]}
    pr_by_id = {p["id"]: p for p in reg["principles"]}

    L = [f"# {ph['id']} · {ph['name']}（{ph['zh']}）", ""]
    L.append(f"> {ph['purpose']}")
    L.append("")

    L.append("## 开工前必须已在手")
    if ph.get("required_inputs"):
        for aid in ph["required_inputs"]:
            a = a_by_id[aid]
            L.append(f"- **{aid} {a['zh']}** —— 产出方 `{a['producer']}`。"
                     f"拿不到就退回，不要靠猜补齐。")
    else:
        L.append("- 无。这是入口阶段。")
    L.append("")

    L.append("## 默认装配")
    L.append("")
    L.append("| 角色 | 心智模型 | 可用技能 |")
    L.append("|---|---|---|")
    for rid in ph.get("default_roles", []):
        r = r_by_id[rid]
        sk = "、".join(f"`{x}`" for x in r.get("skills", [])) or "—"
        L.append(f"| `{rid}` {r['zh']} | "
                 f"{len(r.get('principles', []))} 条 | {sk} |")
    L.append("")
    L.append("阶段只规定判据，不绑定角色。换人换会话，判据不变。")
    L.append("")

    L.append("## 退出判据")
    L.append("")
    for c in ph.get("exit_criteria", []):
        L.append(f"- {c}")
    L.append("")
    if ph.get("hard_rules"):
        L.append("## 硬规则")
        L.append("")
        for h in ph["hard_rules"]:
            L.append(f"- {h}")
        L.append("")

    L.append("## 产出")
    L.append("")
    for aid in ph.get("produces", []):
        a = a_by_id[aid]
        L.append(f"### {aid} · {a['zh']}（`{a['key']}`）")
        L.append("")
        L.append(f"产出方：`{a['producer']}`　持久性：`{a['persistence']}`"
                 f"{'（append-only）' if a.get('append_only') else ''}")
        L.append("")
        L.append("| 字段 | 含义 |")
        L.append("|---|---|")
        for f in a["fields"]:
            L.append(f"| `{f}` | {a.get('notes', {}).get(f, '')} |")
        L.append("")
    if not ph.get("produces"):
        L.append("- 无。本阶段不新增产物，它消费上游已经冻结的东西。")
        L.append("")

    L.append("---")
    L.append(BEGIN)
    L.append(f"<!-- 阶段 {ph['id']} 的结构由 workflow/registry.yaml 派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def ribbon_doc(rb, reg):
    s_by_id = {s["id"]: s for s in reg["skills"]}
    L = [f"# 横切带 · {rb['zh']}（`{rb['id']}`）", ""]
    L.append(f"> {rb['why']}")
    L.append("")
    L.append(f"常驻：`{'是' if rb.get('always') else '否'}`")
    if not rb.get("always"):
        L.append(f"适用范围：{', '.join(rb.get('applies_to', []))}")
    L.append("")
    L.append("## 携带的技能")
    L.append("")
    for sid in rb.get("skills", []):
        s = s_by_id[sid]
        L.append(f"- `{sid}` **{s['zh']}** —— {s['summary']}")
    L.append("")
    L.append("横切带不属于任何阶段：它随装配进入，会话结束后不留下需要「完成」的东西。")
    L.append("")
    L.append("---")
    L.append(BEGIN)
    L.append(f"<!-- 横切带 {rb['id']} 的结构由 workflow/registry.yaml 派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def artifacts_doc(reg):
    L = ["# 集合 A · 工作流的全部产物", "",
         "一个**产物**不是一份文件，是「一组字段 + 谁产出 + 谁消费 + 活多久」。",
         "它落在下游仓库的哪个路径，由 `driver` 按集合 B 裁定——",
         "纪律是本库的，位置是下游的。见 [下游映射](downstream-mapping.md)。", ""]
    L.append("## 总表")
    L.append("")
    L.append("| id | 产物 | 产出方 | 消费者 | 持久性 | 为什么需要它 |")
    L.append("|---|---|---|---|---|---|")
    for a in reg["artifacts"]:
        L.append(f"| {a['id']} | **{a['zh']}** `{a['key']}` | `{a['producer']}` | "
                 f"{'、'.join(a['consumers'])} | `{a['persistence']}`"
                 f"{' append-only' if a.get('append_only') else ''} | {a['rationale']} |")
    L.append("")
    L.append("## 字段")
    L.append("")
    for a in reg["artifacts"]:
        L.append(f"### {a['id']} · {a['zh']}")
        L.append("")
        for f in a["fields"]:
            L.append(f"- `{f}` — {a.get('notes', {}).get(f, '')}")
        L.append("")
    L.append("## 三条不可协商的落盘纪律")
    L.append("")
    L.append("1. **`persistent` 的产物必须有可追溯的落点。** 找不到位置就问 Owner，"
             "不要塞进临时目录——丢掉的记录等于没做过。")
    L.append("2. **`session` 级的产物不进版本库。** 它是判断的输入，不是交付物。")
    L.append("3. **台账只追加。** 不修改、不删除既有行。写错了就再写一行说明为什么错。")
    L.append("")
    L.append("---")
    L.append(BEGIN)
    L.append("<!-- 本文件由 workflow/registry.yaml 的 artifacts 段派生 -->")
    L.append(END)
    L.append("")
    return "\n".join(L)


def closure_doc(reg):
    a_by_id = {a["id"]: a for a in reg["artifacts"]}
    p_by_id = {p["id"]: p for p in reg["phases"]}
    r_by_id = {r["id"]: r for r in reg["roles"]}
    rb_produced = {a for rb in reg["ribbons"] if rb.get("always") for a in rb.get("produces", [])}
    aid_list = [a["id"] for a in reg["artifacts"]]

    L = ["# 闭包报告", "",
         "这份报告回答一个问题：**这套工作流通不通？**",
         "它由 `workflow/registry.yaml` 派生，由 `check-closure.py` 核对。",
         "", "## 产物链", "",
         "| 产物 | 谁产出 | 谁消费 | 在哪一步被校验 |",
         "|---|---|---|---|"]

    validated_at = {}
    for ph in reg["phases"]:
        for crit in ph.get("exit_criteria", []):
            for aid in {x.split(".")[0] for x in crit.split() if x[:2] in ("A1", "A2", "A3",
                         "A4", "A5", "A6", "A7", "A8", "A9") and "." in x}:
                validated_at.setdefault(aid, ph["id"])
    for aid in aid_list:
        a = a_by_id[aid]
        if aid in rb_produced:
            who = "常驻横切带"
        else:
            owner_ph = next((q["id"] for q in reg["phases"] if aid in q.get("produces", [])), None)
            who = owner_ph if owner_ph else "**没有任何阶段产出它**"
        L.append(f"| **{aid} {a['zh']}** | `{a['producer']}` | "
                 f"{'、'.join(a['consumers'])} | {who} |")

    L += ["", "## 阶段链", "", "| 阶段 | 开工需要 | 产出 | 默认装配 |", "|---|---|---|---|"]
    for ph in reg["phases"]:
        L.append(f"| **{ph['id']} {ph['name']}** | "
                 f"{'、'.join(ph.get('required_inputs', [])) or '—'} | "
                 f"{'、'.join(ph.get('produces', [])) or '—'} | "
                 f"{'、'.join(ph.get('default_roles', []))} |")

    L += ["", "## 闭包的三条断言", "",
          "1. **每个产物有且只有一个产出方**，且被至少一个阶段消费。",
          "2. **每个阶段开工所需的产物，在它之前已经被产出**"
          "（或由常驻横切带从第一个阶段起就在写）。",
          "3. **产出某产物的阶段，必须在自己的退出判据里校验它**——"
          "否则下游拿到的是一份没人验证过的东西。", "",
          "第 3 条是上一版最缺的一条：上一版有阶段、有产物、有收据，",
          "但没有任何一处要求「产出它的阶段必须当场验证它」。",
          "结果就是下游拿着上游没验过的东西继续干活。", "",
          "---", "", BEGIN, "<!-- 本文件由 workflow/registry.yaml 派生 -->", END, ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    reg = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))

    targets = {}
    for ph in reg["phases"]:
        targets[ROOT / "workflow" / "phases" / f"{ph['id']}.md"] = phase_doc(ph, reg)
    for rb in reg["ribbons"]:
        targets[ROOT / "workflow" / "ribbons" / f"{rb['id']}.md"] = ribbon_doc(rb, reg)
    targets[ROOT / "docs" / "artifacts.md"] = artifacts_doc(reg)
    targets[ROOT / "docs" / "closure-report.md"] = closure_doc(reg)

    problems = []
    for path, content in sorted(targets.items()):
        if args.check:
            if not path.is_file():
                problems.append(f"{path.relative_to(ROOT)} 不存在")
            elif read(path) != content:
                problems.append(f"{path.relative_to(ROOT)} 与真源不一致")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.is_file() and read(path) == content:
                continue
            path.write_text(content, encoding="utf-8")
            print(f"生成 {path.relative_to(ROOT)}")

    if args.check:
        if problems:
            print("render --check: FAIL")
            for p in problems:
                print(f"  ↳ {p}")
            return 1
        print(f"render --check: OK（{len(targets)} 个派生文件逐字一致）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
