#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""render-ledger.py · 把 SOURCES.md 里的「规则 key」渲染成真实的落点与原文（fail closed）

为什么存在
  `SOURCES.md` 的落点以前是人手写的，于是"步骤号写错""声称的动作不存在"这两类错
  只能靠抽样人核，反复失败。改成生成物以后：**人写 key，脚本填锚点与原文**，key 找不到
  就直接报错——那两类错在构造上不可能出现。

人写什么（唯一的人工面）
  表格里的落点列写 `@<key 短语>`，多条用 `；` 分隔。key 必须是目标角色文件里
  **某一条规则的实质短语**（例如 `注释只写 why`）。key 与普通说明文字可以混排，脚本只认 `@` 开头到 `；` 的部分。

脚本做什么
  1. 从 `roles/*.md` 抽出全部"规则行"（编号步骤 / 判断依据 / 条目 / 表行），连同它所在的
     `## 节` 与 `### 小节`。
  2. 对每个 key 做**子串定位**：
     - 命中 0 处 → 非零退出并列出该 key（规则被删了或被改了措辞）
     - 命中 ≥2 处 → 非零退出并列出全部命中（歧义：key 不够独特）
     - 目标文件不存在 → 非零退出
  3. 把「文件 · 节 · 小节 · 行类型与编号 · 该行原文」写进标记包裹的生成区。

生成区（不得手工编辑）
  <!-- BEGIN:landings (generated by scripts/render-ledger.py · 不得手工改) -->
  …
  <!-- END:landings -->

用法
  render-ledger.py            # 刷新生成区（写文件）
  render-ledger.py --check    # 只比较：与磁盘上的生成区逐字一致才退出 0

退出码：0 = 成功（或 --check 一致）；1 = key 问题；2 = 生成区标记缺失/损坏。
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "SOURCES.md")
ROLES_DIR = os.path.join(ROOT, "roles")

BEGIN = "<!-- BEGIN:landings (generated by scripts/render-ledger.py · 不得手工改) -->"
END = "<!-- END:landings -->"

RE_KEY = re.compile(r"@([^；;|\n]+)")
RE_H2 = re.compile(r"^##\s+(\d+)\.\s*(.+?)\s*$")
RE_H3 = re.compile(r"^###\s+(\d+\.\d+)\s*(.+?)\s*$")
RE_STEP = re.compile(r"^(\d+)\.\s+(.*)$")
RE_BULLET = re.compile(r"^-\s+(.*)$")
RE_TABLE = re.compile(r"^\|\s*(.*?)\s*\|\s*$")


def strip_md(s: str) -> str:
    s = s.replace("**", "").replace("`", "")
    s = re.sub(r"\s+", " ", s)
    return s.strip()


class Rule:
    """一条可被 key 定位的规则行。"""

    def __init__(self, path: str, sec: str, sec_title: str, sub: str, sub_title: str,
                 kind: str, num: str, text: str) -> None:
        self.path = path
        self.sec = sec
        self.sec_title = sec_title
        self.sub = sub
        self.sub_title = sub_title
        self.kind = kind
        self.num = num
        self.text = strip_md(text)

    def where(self) -> str:
        parts = []
        if self.sub:
            parts.append("§%s%s" % (self.sub, ("「%s」" % self.sub_title) if self.sub_title else ""))
        elif self.sec:
            parts.append("§%s%s" % (self.sec, ("「%s」" % self.sec_title) if self.sec_title else ""))
        if self.kind == "步骤":
            parts.append("第 %s 步" % self.num)
        elif self.kind == "表行":
            parts.append("表格行：%s" % self.num)
        else:
            parts.append(self.kind + (" %s" % self.num if self.num else ""))
        return " · ".join(parts)

    def anchor(self) -> str:
        return "`%s` %s" % (self.path, self.where())


def collect_rules() -> list[Rule]:
    rules: list[Rule] = []
    if not os.path.isdir(ROLES_DIR):
        return rules
    for fn in sorted(os.listdir(ROLES_DIR)):
        if not fn.endswith(".md"):
            continue
        path = "roles/%s" % fn
        sec = sec_title = sub = sub_title = ""
        n_bullet = n_table = 0
        for raw in open(os.path.join(ROLES_DIR, fn), encoding="utf-8").read().splitlines():
            m2 = RE_H2.match(raw)
            if m2:
                sec, sec_title, sub, sub_title = m2.group(1), m2.group(2), "", ""
                continue
            m3 = RE_H3.match(raw)
            if m3:
                sub, sub_title = m3.group(1), m3.group(2)
                continue
            if not sub and not sec:
                continue
            m = RE_STEP.match(raw)
            if m:
                rules.append(Rule(path, sec, sec_title, sub, sub_title, "步骤", m.group(1), m.group(2)))
                continue
            if raw.startswith("**判断依据**"):
                rules.append(Rule(path, sec, sec_title, sub, sub_title, "判断依据", "", raw))
                continue
            if raw.startswith("**产出 ") or raw.startswith("**主收据 ") or raw.startswith("**副收据 "):
                rules.append(Rule(path, sec, sec_title, sub, sub_title, "契约块", "", raw))
                continue
            m = RE_BULLET.match(raw)
            if m:
                n_bullet += 1
                rules.append(Rule(path, sec, sec_title, sub, sub_title, "条目", str(n_bullet), m.group(1)))
                continue
            if not sub and len(strip_md(raw)) >= 12 and not raw.startswith(("|", "#", "-", ">", "```")):
                rules.append(Rule(path, sec, sec_title, sub, sub_title, "整段", "", raw))
                continue
            m = RE_TABLE.match(raw)
            if m and not set(m.group(1)) <= set("-: "):
                cells = [c.strip() for c in m.group(1).split("|")]
                if cells and cells[0] and not cells[0].startswith("字段"):
                    n_table += 1
                    rules.append(Rule(path, sec, sec_title, sub, sub_title, "表行", str(n_table), " | ".join(cells)))
    return rules


def read_keys() -> list[str]:
    """只从表格行的**最后一个单元格**（落点列）读 key——正文里出现的 @ 不是 key。"""
    keys: list[str] = []
    for raw in open(SOURCES, encoding="utf-8").read().splitlines():
        if raw.startswith(BEGIN) or raw.startswith(END) or not raw.startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip().strip("|").split("|")]
        if len(cells) < 2 or set("".join(cells)) <= set("-: "):
            continue
        for m in RE_KEY.finditer(cells[-1]):
            k = m.group(1).strip()
            if k and k not in keys:
                keys.append(k)
    return keys


def render(rules: list[Rule]) -> tuple[str, list[str]]:
    keys = read_keys()
    problems: list[str] = []
    entries: list[str] = []
    for key in keys:
        hits = [r for r in rules if key in r.text]
        if not hits:
            problems.append("key 找不到：@%s" % key)
            continue
        if len(hits) > 1:
            detail = "；".join("%s（%s）" % (h.path, h.where()) for h in hits)
            problems.append("key 有歧义（命中 %d 处）：@%s → %s" % (len(hits), key, detail))
            continue
        r = hits[0]
        entries.append("### @%s\n\n- 落点：%s\n- 原文：%s\n" % (key, r.anchor(), r.text))
    body = "\n".join(entries)
    return body, problems


def read_region() -> str | None:
    text = open(SOURCES, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        return None
    return text.split(BEGIN, 1)[1].split(END, 1)[0]


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    if not os.path.isfile(SOURCES):
        print("SOURCES.md 不存在", file=sys.stderr)
        return 2
    text = open(SOURCES, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        print("生成区标记缺失：需要 %s 与 %s" % (BEGIN, END), file=sys.stderr)
        return 2

    rules = collect_rules()
    body, problems = render(rules)

    if problems:
        print("render-ledger: FAIL（%d 个 key 有问题，fail closed）" % len(problems))
        for p in problems:
            print("  - " + p)
        return 1

    new_region = "\n" + body
    current = read_region()
    head, rest = text.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    rebuilt = head + BEGIN + new_region + END + tail

    n_keys = len(read_keys())
    if check_only:
        if current == new_region:
            print("render-ledger --check: OK（%d 个 key，生成区与重新生成的结果逐字一致）" % n_keys)
            return 0
        print("render-ledger --check: FAIL（生成区与重新生成的结果不一致——有人手工改过生成区，或规则已移动）", file=sys.stderr)
        return 1

    open(SOURCES, "w", encoding="utf-8").write(rebuilt)
    print("render-ledger: 已刷新生成区（%d 个 key，%d 条规则行可定位）" % (n_keys, len(rules)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
